gradle: tar, not tar + zip, in backend distribution
Our builds failed in Gitlab, with the error:

	ERROR: Uploading artifacts to coordinator... too large archive  id=3952 responseStatus=413 Request Entity Too Large status=413 Request Entity Too Large token=y24JsVwQ
	FATAL: Too large
	ERROR: Job failed: exit code 1

This was caused by us trying to distribute both zip and tar artifacts,
which is unnecessary. Let's skip the zip.

Signed-off-by: Carl Helmertz <carl.helmertz@elvaco.se>